%{
%}

%token NUMBER IDENT ID_NUM TERM EXPRESSION COMPOUND_STATEMENT
%token FOR_STATEMENT DO_STATEMENT WHILE_STATEMENT IF_STATEMENT
%token PROCEDURE_CALL ASSIGNMENT STATEMENT IMPLEMENTATION_PART
%token FUNCTION_DECLARATION PROCEDURE_DECLARATION SPECIFICATION_PART
%token BLOCK IMPLEMENTATION_UNIT RANGE ARRAY_TYPE RANGE_TYPE
%token ENUMERATE_TYPE BASIC_TYPE TYPE VARIABLE_DECLARATION
%token TYPE_DECLARATION FUNCTION_INTERFACE PROCEDURE_INTERFACE
%token DECLARATION_UNIT BASIC_PROGRAM

%%

%%
